Repository SSAFY13th-algorithm/Algorithm-study-1, pull requests merged in 2025-03, with the labels that each got.

#31 [박준서-5주차 알고리즘 스터디]
  박준서/5주차/[Baekjoon-14620]꽃길.java
  박준서/5주차/[Baekjoon-15817]배수공사.java
  박준서/5주차/[Baekjoon-17485]진우의달여행Large.java
  박준서/5주차/[Baekjoon-1802]종이접기.java
  박준서/5주차/[Baekjoon19237]어른상어.java
Labels: 😊5주차

#36 [김민진-5주차 알고리즘 스터디]
  김민진/4주차/[Baekjoon-19236] 청소년 상어.java
  김민진/5주차/[Baekjoon-14620] 꽃길.java
  김민진/5주차/[Baekjoon-15817] 배수 공사.java
  김민진/5주차/[Baekjoon-17485] 진우의 달 여행 (Large).java
  김민진/5주차/[Baekjoon-1802] 종이 접기.java
  김민진/5주차/[Baekjoon-19237] 어른 상어.java
Labels: 😊5주차

#38 [김동하-5주차 알고리즘 스터디]
  김동하/5주차/[백준 14620] 꽃길.java
  김동하/5주차/[백준 15817] 배수 공사.java
  김동하/5주차/[백준 17485] 진우의 달 여행_Large.java
  김동하/5주차/[백준 1802] 종이 접기.java
  김동하/5주차/[백준 19237] 어른 상어.java
Labels: 😊5주차

#41 [박준서-6주차 알고리즘 스터디]
  박준서/6주차/[Baekjun-1080]행렬.java
  박준서/6주차/[Baekjun-1437]수분해.java
  박준서/6주차/[Baekjun-16472]고냥이.java
  박준서/6주차/[Baekjun-1717]집합의표현.java
  박준서/6주차/[Baekjun-20056]마법사상어와파이어볼.java
Labels: 🤔6주차

#39 [박예진-6주차 알고리즘 스터디]
  박예진/6주차/[백준 1080] 행렬.cpp
  박예진/6주차/[백준 16472] 고냥이.cpp
  박예진/6주차/[백준 1717] 집합의 표현.cpp
  박예진/6주차/[백준 20056] 마법사 상어와 파이어볼.cpp
Labels: 🤔6주차

#42 [문한결-6주차 알고리즘 스터디]
  문한결/6주차/고냥이.java
  문한결/6주차/수분해.java
  문한결/6주차/집합의표현.java
  문한결/6주차/파이어볼.java
  문한결/6주차/행렬.java
Labels: 🤔6주차

#45 [김동하-6주차 알고리즘 스터디]
  김동하/6주차/[백준 1080] 행렬.java
  김동하/6주차/[백준 1437] 수 분해.java
  김동하/6주차/[백준 16472] 고냥이.java
  김동하/6주차/[백준 1717] 집합의 표현.java
  김동하/6주차/[백준 20056] 마법사상어와파이어볼.java
Labels: 🤔6주차

#43 [김민진-6주차 알고리즘 스터디]
  김민진/6주차/[Baekjoon-1080] 행렬.java
  김민진/6주차/[Baekjoon-16472] 고냥이.java
  김민진/6주차/[Baekjoon-1717] 집합의 표현.java
  김민진/6주차/[Baekjoon-20056] 마법사 상어와 파이어볼.java
  김민진/6주차/[Baekjun-1437] 수 분해.java
Labels: 🤔6주차

#44 [이종환-6주차 알고리즘 스터디]
  이종환/6주차/고냥이.java
  이종환/6주차/수분해.java
  이종환/6주차/집합의표현.java
  이종환/6주차/행렬.java
Labels: 🤔6주차

#51 [박준서-7주차 알고리즘 스터디]
  박준서/7주차/[Baekjoon-15724]주지수.java
  박준서/7주차/[Baekjoon-17822]원판돌리기.java
  박준서/7주차/[Baekjoon-1823]수확.java
  박준서/7주차/[Baekjoon-20057]마법사상어와토네이도.java
  박준서/7주차/[Baekjoon-2098]외판원순회.java
  박준서/7주차/[Baekjun-19585]전설.cpp
Labels: 📝7주차

#46 [박예진-7주차 알고리즘 스터디]
  박예진/7주차/[백준 15724] 주지수.cpp
  박예진/7주차/[백준 17822] 원판 돌리기.cpp
  박예진/7주차/[백준 1823] 수확.cpp
  박예진/7주차/[백준 20057] 마법사 상어와 토네이도.cpp
Labels: 📝7주차

#50 [김민진-7주차 알고리즘 스터디]
  김민진/7주차/[Baekjoon-15724] 주지수.java
  김민진/7주차/[Baekjoon-17822] 원판 돌리기.java
  김민진/7주차/[Baekjoon-1823] 수확.java
  김민진/7주차/[Baekjoon-2098] 외판원 순회.java
Labels: 📝7주차

#48 [문한결-7주차 알고리즘 스터디]
  문한결/7주차/수확.java
  문한결/7주차/원판돌리기.java
  문한결/7주차/주지수.java
  문한결/7주차/토네이도.java
Labels: 📝7주차

#47 [김동하-7주차 알고리즘 스터디]
  김동하/7주차/[백준 15724] 주지수.java
  김동하/7주차/[백준 17822] 원판돌리기 .java
  김동하/7주차/[백준 1823] 수확.java
  김동하/7주차/[백준 20057] 마법사상어와토네이도.java
  김동하/7주차/[백준 2098] 외판원 순회.java
Labels: 📝7주차

#53 [박예진-8주차 알고리즘 스터디]
  박예진/8주차/[백준 15787] 기차가 어둠을 헤치고 은하수를.cpp
  박예진/8주차/[백준 20055] 컨베이어 벨트 위의 로봇.cpp
  박예진/8주차/[백준 20058] 마법사 상어와 파이어스톰.cpp
  박예진/8주차/[백준 2151] 거울 설치.cpp
  박예진/8주차/[백준 28075] 스파이.cpp
Labels: 🔥8주차

#56 [김민진-8주차 알고리즘 스터디]
  김민진/7주차/[20057] 마법사 상어와 토네이도.java
  김민진/8주차/[Baekjoon-15787] 기차가 어둠을 헤치고 은하수를.java
  김민진/8주차/[Baekjoon-20055] 컨베이어 벨트 위의 로봇.java
  김민진/8주차/[Baekjoon-20058] 마법사 상어와 파이어스톰.java
  김민진/8주차/[Baekjoon-2151] 거울 설치.java
  김민진/8주차/[Baekjoon-28075] 스파이.java
Labels: 🔥8주차

#52 [김동하-8주차 알고리즘 스터디]
  김동하/8주차/[백준 15787] 기차가 어둠을 헤치고 은하수를.java
  김동하/8주차/[백준 20055] 컨베이어 벨트 위의 로봇.java
  김동하/8주차/[백준 20058] 마법사 상어와 파이어스톰.java
  김동하/8주차/[백준 2151] 거울 설치.java
  김동하/8주차/[백준 28075] 스파이.java
Labels: 🔥8주차

#57 [문한결-8주차 알고리즘 스터디]
  문한결/7주차/외판원.java
  문한결/8주차/거울설치.java
  문한결/8주차/스파이.java
  문한결/8주차/은하수.java
  문한결/8주차/컨베이어.java
  문한결/8주차/파이어스톰.java
Labels: 🔥8주차

#54 [박준서-8주차 알고리즘 스터디]
  박준서/8주차/[Baekjoon-15787]기차가어둠을헤치고은하수를.java
  박준서/8주차/[Baekjoon-20055]컨베이어벨트위의로봇.java
  박준서/8주차/[Baekjoon-20058]마법사상어와파이어스톰.java
  박준서/8주차/[Baekjoon-2151].거울설치.java
  박준서/8주차/[Baekjoon-28075]스파이.java
Labels: 🔥8주차

#59 [박예진-9주차 알고리즘 스터디]
  박예진/9주차/[백준 1389] 케빈 베이컨의 6단계 법칙.cpp
  박예진/9주차/[백준 21610] 마법사 상어와 비바라기.cpp
  박예진/9주차/[백준 2531] 회전초밥.cpp
  박예진/9주차/[백준 2637] 장난감 조립.cpp
  박예진/9주차/[백준 5052] 전화번호 목록.cpp
Labels: 9️⃣9주차

#62 [박준서-9주차 알고리즘스터디]
  박준서/9주차/[Baekjoon-10999]구간합구하기2.java
  박준서/9주차/[Baekjoon-1389]케빈베이컨의6단계법칙.java
  박준서/9주차/[Baekjoon-21610]마법사상어와비바라기.java
  박준서/9주차/[Baekjoon-2531]회전초밥.java
  박준서/9주차/[Baekjoon-2637]장난감조립.java
  박준서/9주차/[Baekjoon-5052]전화번호목록.java
Labels: 9️⃣9주차

#64 [김민진-9주차 알고리즘 스터디]
  김민진/9주차/[Baekjoon-1389] 케빈 베이컨의 6단계 법칙.java
  김민진/9주차/[Baekjoon-21610] 마법사 상어와 비바라기.java
  김민진/9주차/[Baekjoon-2531] 회전초밥.java
  김민진/9주차/[Baekjoon-2637] 장난감 조립.java
  김민진/9주차/[Baekjoon-5052] 전화번호 목록.java
Labels: 9️⃣9주차

#60 [문한결-9주차 알고리즘스터디]
  문한결/9주차/비바라기.java
  문한결/9주차/장난감.java
  문한결/9주차/전화번호.java
  문한결/9주차/초밥.java
  문한결/9주차/케빈.java
Labels: 9️⃣9주차

#63 [이종환-9주차 알고리즘스터디]
  이종환/9주차/마법사상어와_비바라기.java
  이종환/9주차/장난감조립.java
  이종환/9주차/전화번호목록.java
  이종환/9주차/케빈베이컨의_6단계법칙.java
  이종환/9주차/회전초밥.java
Labels: 9️⃣9주차

#58 [김동하-9주차 알고리즘 스터디]
  김동하/9주차/[백준 1389] 케빈베이컨의 6단계 법칙.java
  김동하/9주차/[백준 21610] 마법사 상어와 비바라기.java
  김동하/9주차/[백준 2531] 회전 초밥.java
  김동하/9주차/[백준 2637] 장난감 조립.java
  김동하/9주차/[백준 5052] 전화번호 목록.java
Labels: 9️⃣9주차

#66 [박준서-10주차 알고리즘 스터디]
  박준서/10주차/[Baekjoon-10815]숫자카드.java
  박준서/10주차/[Baekjoon-11000]강의실배정.java
  박준서/10주차/[Baekjoon-14391]종이조각.java
  박준서/10주차/[Baekjoon-2143]두배열의합.java
  박준서/10주차/[Baekjoon-21611]마법사상어와블리자드.java
Labels: 😮10주차
