Repository SSAFY13th-algorithm/Algorithm-study-1, pull requests merged in 2025-02, with the labels that each got.

#3 [김동하-1주차 알고리즘 스터디]
  김동하/1주차/[Baekjoon-10844] 쉬운 계단 수.java
  김동하/1주차/[Baekjoon-17070] 파이프 옮기기 1.java
  김동하/1주차/[Baekjoon-17471] 게리맨더링.java
  김동하/1주차/[Baekjoon-17472] 다리 만들기 2.java
  김동하/1주차/[Baekjoon-2578] 빙고.java
Labels: 📖1주차

#12 [김동하-2주차 알고리즘 스터디]
  김동하/2주차/[백준 1309] 동물원.java
  김동하/2주차/[백준 1629] 곱셈.java
  김동하/2주차/[백준 17845] 수강 과목.java
  김동하/2주차/[백준 18352] 특정 거리의 도시 찾기.java
  김동하/2주차/[백준 21608] 상어 초등학교.java
Labels: 😢2주차

#7 [김민진-1주차 알고리즘 스터디]
  김민진/1주차/[Baekjoon-10844] 쉬운 계단 수.java
  김민진/1주차/[Baekjoon-17070] 파이프 옮기기 1.java
  김민진/1주차/[Baekjoon-17471] 게리맨더링.java
  김민진/1주차/[Baekjoon-17472] 다리 만들기 2.java
  김민진/1주차/[Baekjoon-2578] 빙고.java
  김민진/1주차/inital.txt
Labels: 📖1주차

#5 [문한결-1주차 알고리즘 스터디]
  문한결/1주차/문제1-다리 만들기2.java
  문한결/1주차/문제2-게리맨더링.java
  문한결/1주차/문제3-파이프 옮기기.java
  문한결/1주차/문제4-빙고.java
  문한결/1주차/문제5-쉬운 계단수.java
Labels: 📖1주차

#20 [김동하-3주차 알고리즘 스터디]
  김동하/3주차/[백준 13305] 주유소.java
  김동하/3주차/[백준 16236] 아기 상어.java
  김동하/3주차/[백준 1931] 회의실 배정.java
  김동하/3주차/[백준 2981] 검문.java
  김동하/3주차/[백준 9020] 골드바흐의 추측.java
Labels: ✨3주차

#13 [문한결-2주차 알고리즘 스터디]
  문한결/2주차/곱셈.java
  문한결/2주차/동물원.java
  문한결/2주차/상어초등학교.java
  문한결/2주차/수강 과목.java
  문한결/2주차/특정 거리의 도시찾기.java
Labels: 😢2주차

#19 [문한결-3주차 알고리즘 스터디]
  문한결/3주차/검문.java
  문한결/3주차/골드 바흐의 추측.java
  문한결/3주차/아기상어.java
  문한결/3주차/주유소.java
  문한결/3주차/회의실 배정.java
Labels: ✨3주차

#15 [박준서-2주차 알고리즘 스터디]
  박준서/2주차/[Baekjun-1309]동물원.java
  박준서/2주차/[Baekjun-1629]곱셈.java
  박준서/2주차/[Baekjun-17845]수강과목.java
  박준서/2주차/[Baekjun-18352]특정거리의도시찾기.java
  박준서/2주차/[Baekjun-21608]상어초등학교.java
Labels: 😢2주차

#23 [박준서-3주차 알고리즘 스터디]
  박준서/3주차/[Baekjun-13305]주유소.java
  박준서/3주차/[Baekjun-16236]아기상어.java
  박준서/3주차/[Baekjun-1931]회의실배정.java
  박준서/3주차/[Baekjun-2981]검문.java
  박준서/3주차/[Baekjun-9020]골드바흐의추측.java
Labels: ✨3주차

#9 [박예진-1주차 알고리즘 스터디]
  박예진/1주차/[백준 10844] 쉬운 계단 수.java
  박예진/1주차/[백준 17070] 파이프 옮기기 1.java
  박예진/1주차/[백준 17471] 게리맨더링.java
  박예진/1주차/[백준 17472] 다리 만들기 2.java
  박예진/1주차/[백준 2578] 빙고.java
  박예진/2주차/[백준 1629] 곱셈.java
  박예진/2주차/[백준 17845] 수강과목.java
  박예진/2주차/[백준 18352] 특정 거리의 도시 찾기.java
  박예진/2주차/[백준 21608] 상어 초등학교.java
Labels: 📖1주차

#14 [박예진-2주차 알고리즘 스터디]
  박예진/2주차/[백준 1309] 동물원.java
  박예진/2주차/[백준 1629] 곱셈.java
  박예진/2주차/[백준 17845] 수강과목.java
  박예진/2주차/[백준 18352] 특정 거리의 도시 찾기.java
  박예진/2주차/[백준 21608] 상어 초등학교.java
Labels: 😢2주차

#18 [박예진-3주차 알고리즘 스터디]
  박예진/3주차/[백준 13305] 주유소.java
  박예진/3주차/[백준 16236] 아기 상어.java
  박예진/3주차/[백준 1931] 회의실 배정.java
  박예진/3주차/[백준 2981] 검문.java
  박예진/3주차/[백준 9020] 골드바흐의 추측.java
Labels: ✨3주차

#8 [정민서-1주차 알고리즘 스터디]
  정민서/1주차/[Baekjoon-10844] 쉬운 계단 수.java
  정민서/1주차/[Baekjoon-17070] 파이프 옮기기 1.java
  정민서/1주차/[Baekjoon-17471] 게리맨더링.java
  정민서/1주차/[Baekjoon-17472] 다리만들기.java
  정민서/1주차/[Baekjoon-2578] 빙고.java
  정민서/1주차/inital.txt
  정민서/2주차/[Baekjoon-1309] 동물원.java
  정민서/2주차/[Baekjoon-1629] 곱셈.java
  정민서/2주차/[Baekjoon-17845] 수강 과목.java
  정민서/2주차/[Baekjoon-18352] 특정 거리의 도시 찾기.java
  정민서/3주차/[Baekjoon-13305] 주유소.java
  정민서/3주차/[Baekjoon-9020] 골드바흐의 추측.java
Labels: 📖1주차

#24 [박예진-4주차 알고리즘 스터디]
  박예진/4주차/[백준 11478] 서로 다른 부분 문자열의 개수.java
  박예진/4주차/[백준 1254] 팰린드롬 만들기.java
  박예진/4주차/[백준 1865] 웜홀.java
  박예진/4주차/[백준 19236] 청소년 상어.java
  박예진/4주차/[백준 5972] 택배 배송.java
Labels: 👍4주차

#26 [박준서-4주차 알고리즘 스터디]
  박준서/4주차/[Baekjun-11478]서로다른부분문자열의개수.java
  박준서/4주차/[Baekjun-1254]팰린드롬만들기.java
  박준서/4주차/[Baekjun-1865]웜홀.java
  박준서/4주차/[Baekjun-19236]청소년상어.java
  박준서/4주차/[Baekjun-5972]택배배송.java
Labels: 👍4주차

#27 [문한결-4주차 알고리즘 스터디]
  문한결/4주차/서로 다른 부분 문자열의 개수.java
  문한결/4주차/웜홀.java
  문한결/4주차/택배 배송.java
  문한결/4주차/펠린드롬 만들기2.java
Labels: 👍4주차

#30 [박예진-5주차 알고리즘 스터디]
  박예진/5주차/[백준 14620] 꽃길.java
  박예진/5주차/[백준 15817] 배수 공사.java
  박예진/5주차/[백준 17485] 진우의 달 여행.java
  박예진/5주차/[백준 1802] 종이 접기.java
Labels: 😊5주차
